#define EE_HANDS


#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#undef WS2812_DI_PIN
#define WS2812_DI_PIN 25
#undef RGBLIGHT_LED_COUNT
#define RGBLIGHT_LED_COUNT 2
#undef RGBLED_SPLIT
#define RGBLED_SPLIT {1, 1}
#undef RGBLED_SPLIT
#define RGBLIGHT_SPLIT {1, 1}
#define SPLIT_LED_STATE_ENABLE

#define MOUSEKEY_INTERVAL    16
#define MOUSEKEY_MAX_SPEED   7
#define MOUSEKEY_TIME_TO_MAX 60

#define TAPPING_TERM 300
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define ACHORDION_STREAK

#define COMBO_TERM 30
#define COMBO_TERM_PER_COMBO
